dist: bionic
language: go
env: GO111MODULE=on GOFLAGS='-mod vendor'
install: true
email: false

go:
  - 1.10
  - 1.11
  - 1.12
  - 1.13
  - tip

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - go test -v -race ./...  # Run all the tests with the race detector enabled

  #  - go test -v -cover
  - $HOME/gopath/bin/goveralls -v -service=travis-ci
